[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your-project-name"
version = "0.1.0"
dependencies = [
    "fastapi==0.115.0",
    "uvicorn[standard]==0.30.6",
    "markitdown @ git+https://github.com/microsoft/markitdown"
] 